plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  fastify-static@*:
    peerDependencies:
      fastify: "*"
  fastify-oauth2@*:
    peerDependencies:
      fastify: "*"
  fastify-jwt@*:
    peerDependencies:
      fastify: "*"
  fastify-cookie@*:
    peerDependencies:
      fastify: "*"
  mercurius@*:
    peerDependencies:
      fastify: "*"
